# Deploy to Railway staging environment after creating a pre-release on Github
name: Deploy to Railway Staging Environment

on: 
  workflow_dispatch:
  release: 
    types: [published]

permissions:
  contents: read
  packages: read

jobs:
  get-some-vars:
    name: Get some vars
    runs-on: ubuntu-latest
    outputs:
      repo_name: ${{ steps.get_repo_name.outputs.repo_name }}
    steps:
      - name: Dump Github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "GITHUB_CONTEXT: $GITHUB_CONTEXT"

      - id: get_repo_name
        run: |
          repo_name=$(echo ${{github.repository}} | awk -F '/' '{print $2}')
          echo "repo_name=$repo_name" >> $GITHUB_OUTPUT
        shell: bash

  deploy-to-railway:
    name: Deploying ${{matrix.service_name }}
    needs: get-some-vars
    strategy:
      fail-fast: false
      matrix:
        service_name: 
          - ${{ needs.get-some-vars.outputs.repo_name }}
        railway_environment: 
          - "slate-staging"
          - "jasper-staging"
          - "legal-staging"
    uses: ginkgoo-ai/do-actions/.github/workflows/deploy-to-railway.yml@main
    with:
      service_name: ${{ matrix.service_name }}
      railway_environment: ${{ matrix.railway_environment }}
    secrets:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

